-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, USR.GENDER GENDER, COUNT(DISTINCT SALE.USER_ID)USERS
FROM USER_INFO USR INNER JOIN ONLINE_SALE SALE
ON USR.USER_ID = SALE.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3;