SELECT BO.WRITER_ID, US.NICKNAME, SUM(BO.PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD BO 
    JOIN USED_GOODS_USER US
    ON BO.WRITER_ID = US.USER_ID
WHERE BO.STATUS = 'DONE' 
GROUP BY BO.WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;