-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY,
       SUM((B.PRICE * BS.SALES)) AS TOTAL_SALES
FROM BOOK B, AUTHOR A, BOOK_SALES BS
WHERE B.BOOK_ID = BS.BOOK_ID AND B.AUTHOR_ID = A.AUTHOR_ID
AND BS.SALES_DATE LIKE '2022-01%'
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY 1, 3 DESC;