-- 코드를 입력하세요
SELECT INFO.REST_ID REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE),2) SCORE
FROM REST_INFO INFO JOIN REST_REVIEW REV
ON INFO.REST_ID = REV.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY INFO.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;